import type { Metadata } from "next";
import { NotoSerifTC } from "@/helpers/fontHelper";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={NotoSerifTC.className}>
      <body>
        <header className="h-[48px] fixed top-0 left-0 right-0">
          <nav className="container h-full mx-auto"></nav>
        </header>
        <main className="pt-[48px]">{children}</main>
      </body>
    </html>
  );
}
