import type { Metadata } from "next";
import { NotoSerifTC } from "@/helpers/fontHelper";
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={NotoSerifTC.className}>
      <body>
        <header className="h-[48px]"></header>
        <main>{children}</main>
      </body>
    </html>
  );
}
